version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"  # Porta MQTT
      - "9001:9001"  # Porta para WebSockets (opcional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

networks:
  promoflash-network:
    driver: bridge